TARGET = replace_dir_backslash

main:
	gcc replace_dir_backslash.c -o  $(TARGET)
	 ./replace_dir_backslash "C:\Users\Administrator\Desktop\temp\autio_process\two"

install:
	sudo cp $(TARGET) /usr/bin

uninstall:
	sudo rm /usr/bin/$(TARGET)

